// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'staging_firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTz8b655tJ5ojaE-lbqDSVSGDPhD4TEz0',
    appId: '1:542211545657:android:0bf2301aa9ea76f08bcbe8',
    messagingSenderId: '542211545657',
    projectId: 'flutter-starter-kit-77ebd',
    storageBucket: 'flutter-starter-kit-77ebd.appspot.com',
  );

  // TODO: Regenate the FirebaseOptions for your project using FlutterFire CLI

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL4_TxXnp35Y3SprGaumI2tyFQ3AVypT0',
    appId: '1:542211545657:ios:56f50b5089f5f8088bcbe8',
    messagingSenderId: '542211545657',
    projectId: 'flutter-starter-kit-77ebd',
    storageBucket: 'flutter-starter-kit-77ebd.appspot.com',
    iosBundleId: 'com.dumbdumb.my.stag',
  );

}